export default {
	phoneLength:[
		{"name": "Afghanistan", "phone_code": "+93", "phone_length": 9},
		{"name": "Albania", "phone_code": "+355", "phone_length": 9},
		{"name": "Algeria", "phone_code": "+213", "phone_length": 9},
		{"name": "American Samoa", "phone_code": "+1-684", "phone_length": 7},
		{"name": "Andorra", "phone_code": "+376", "phone_length": 6},
		{"name": "Angola", "phone_code": "+244", "phone_length": 9},
		{"name": "Anguilla", "phone_code": "+1-264", "phone_length": 7},
		{"name": "Antarctica", "phone_code": "N/A", "phone_length": 0},
		{"name": "Antigua and Barbuda", "phone_code": "+1-268", "phone_length": 7},
		{"name": "Argentina", "phone_code": "+54", "phone_length": 10},
		{"name": "Armenia", "phone_code": "+374", "phone_length": 8},
		{"name": "Aruba", "phone_code": "+297", "phone_length": 7},
		{"name": "Australia", "phone_code": "+61", "phone_length": 9},
		{"name": "Austria", "phone_code": "+43", "phone_length": 10},
		{"name": "Azerbaijan", "phone_code": "+994", "phone_length": 9},
		{"name": "Bahamas", "phone_code": "+1-242", "phone_length": 7},
		{"name": "Bahrain", "phone_code": "+973", "phone_length": 8},
		{"name": "Bangladesh", "phone_code": "+880", "phone_length": 10},
		{"name": "Barbados", "phone_code": "+1-246", "phone_length": 7},
		{"name": "Belarus", "phone_code": "+375", "phone_length": 9},
		{"name": "Belgium", "phone_code": "+32", "phone_length": 9},
		{"name": "Belize", "phone_code": "+501", "phone_length": 7},
		{"name": "Benin", "phone_code": "+229", "phone_length": 9},
		{"name": "Bermuda", "phone_code": "+1-441", "phone_length": 7},
		{"name": "Bhutan", "phone_code": "+975", "phone_length": 8},
		{"name": "Bolivia", "phone_code": "+591", "phone_length": 8},
		{"name": "Bonaire, Sint Eustatius and Saba", "phone_code": "+599", "phone_length": 7},
		{"name": "Bosnia and Herzegovina", "phone_code": "+387", "phone_length": 8},
		{"name": "Botswana", "phone_code": "+267", "phone_length": 7},
		{"name": "Bouvet Island", "phone_code": "N/A", "phone_length": 0},
		{"name": "Brazil", "phone_code": "+55", "phone_length": 11},
		{"name": "British Indian Ocean Territory", "phone_code": "N/A", "phone_length": 0},
		{"name": "Brunei Darussalam", "phone_code": "+673", "phone_length": 7},
		{"name": "Bulgaria", "phone_code": "+359", "phone_length": 9},
		{"name": "Burkina Faso", "phone_code": "+226", "phone_length": 8},
		{"name": "Burundi", "phone_code": "+257", "phone_length": 8},
		{"name": "Cabo Verde", "phone_code": "+238", "phone_length": 7},
		{"name": "Cambodia", "phone_code": "+855", "phone_length": 9},
		{"name": "Cameroon", "phone_code": "+237", "phone_length": 9},
		{"name": "Canada", "phone_code": "+1", "phone_length": 10},
		{"name": "Cayman Islands", "phone_code": "+1-345", "phone_length": 7},
		{"name": "Central African Republic", "phone_code": "+236", "phone_length": 8},
		{"name": "Chad", "phone_code": "+235", "phone_length": 8},
		{"name": "Chile", "phone_code": "+56", "phone_length": 9},
		{"name": "China", "phone_code": "+86", "phone_length": 11},
		{"name": "Christmas Island", "phone_code": "+61", "phone_length": 9},
		{"name": "Cocos (Keeling) Islands", "phone_code": "+61", "phone_length": 9},
		{"name": "Colombia", "phone_code": "+57", "phone_length": 10},
		{"name": "Comoros", "phone_code": "+269", "phone_length": 7},
		{"name": "Cook Islands", "phone_code": "+682", "phone_length": 5},
		{"name": "Costa Rica", "phone_code": "+506", "phone_length": 8},
		{"name": "Croatia", "phone_code": "+385", "phone_length": 9},
		{"name": "Cuba", "phone_code": "+53", "phone_length": 8},
		{"name": "Curaçao", "phone_code": "+599", "phone_length": 7},
		{"name": "Cyprus", "phone_code": "+357", "phone_length": 8},
		{"name": "Czech Republic", "phone_code": "+420", "phone_length": 9},
		{"name": "Côte d'Ivoire", "phone_code": "+225", "phone_length": 8},
		{"name": "Democratic Republic of the Congo", "phone_code": "+243", "phone_length": 9},
		{"name": "Denmark", "phone_code": "+45", "phone_length": 8},
		{"name": "Djibouti", "phone_code": "+253", "phone_length": 6},
		{"name": "Dominica", "phone_code": "+1-767", "phone_length": 7},
		{"name": "Dominican Republic", "phone_code": "+1-809", "phone_length": 10},
		{"name": "Ecuador", "phone_code": "+593", "phone_length": 9},
		{"name": "Egypt", "phone_code": "+20", "phone_length": 10},
		{"name": "El Salvador", "phone_code": "+503", "phone_length": 8},
		{"name": "Equatorial Guinea", "phone_code": "+240", "phone_length": 9},
		{"name": "Eritrea", "phone_code": "+291", "phone_length": 7},
		{"name": "Estonia", "phone_code": "+372", "phone_length": 8},
		{"name": "Ethiopia", "phone_code": "+251", "phone_length": 9},
		{"name": "Falkland Islands", "phone_code": "+500", "phone_length": 5},
		{"name": "Faroe Islands", "phone_code": "+298", "phone_length": 6},
		{"name": "Fiji", "phone_code": "+679", "phone_length": 7},
		{"name": "Finland", "phone_code": "+358", "phone_length": 10},
		{"name": "France", "phone_code": "+33", "phone_length": 9},
		{"name": "French Guiana", "phone_code": "+594", "phone_length": 9},
		{"name": "French Polynesia", "phone_code": "+689", "phone_length": 6},
		{"name": "French Southern Territories", "phone_code": "N/A", "phone_length": 0},
		{"name": "Gabon", "phone_code": "+241", "phone_length": 9},
		{"name": "Gambia", "phone_code": "+220", "phone_length": 7},
		{"name": "Georgia", "phone_code": "+995", "phone_length": 9},
		{"name": "Germany", "phone_code": "+49", "phone_length": 10},
		{"name": "Ghana", "phone_code": "+233", "phone_length": 9},
		{"name": "Gibraltar", "phone_code": "+350", "phone_length": 8},
		{"name": "Greece", "phone_code": "+30", "phone_length": 10},
		{"name": "Greenland", "phone_code": "+299", "phone_length": 6},
		{"name": "Grenada", "phone_code": "+1-473", "phone_length": 7},
		{"name": "Guadeloupe", "phone_code": "+590", "phone_length": 9},
		{"name": "Guam", "phone_code": "+1-671", "phone_length": 7},
		{"name": "Guatemala", "phone_code": "+502", "phone_length": 8},
		{"name": "Guernsey", "phone_code": "+44-1481", "phone_length": 6},
		{"name": "Guinea", "phone_code": "+224", "phone_length": 9},
		{"name": "Guinea-Bissau", "phone_code": "+245", "phone_length": 7},
		{"name": "Guyana", "phone_code": "+592", "phone_length": 7},
		{"name": "Haiti", "phone_code": "+509", "phone_length": 8},
		{"name": "Honduras", "phone_code": "+504", "phone_length": 8},
		{"name": "Hong Kong", "phone_code": "+852", "phone_length": 8},
		{"name": "Hungary", "phone_code": "+36", "phone_length": 9},
		{"name": "Iceland", "phone_code": "+354", "phone_length": 7},
		{"name": "India", "phone_code": "+91", "phone_length": 10},
		{"name": "Indonesia", "phone_code": "+62", "phone_length": 10},
		{"name": "Iran", "phone_code": "+98", "phone_length": 10},
		{"name": "Iraq", "phone_code": "+964", "phone_length": 10},
		{"name": "Ireland", "phone_code": "+353", "phone_length": 9},
		{"name": "Isle of Man", "phone_code": "+44-1624", "phone_length": 6},
		{"name": "Israel", "phone_code": "+972", "phone_length": 9},
		{"name": "Italy", "phone_code": "+39", "phone_length": 10},
		{"name": "Jamaica", "phone_code": "+1-876", "phone_length": 7},
		{"name": "Japan", "phone_code": "+81", "phone_length": 10},
		{"name": "Jersey", "phone_code": "+44-1534", "phone_length": 6},
		{"name": "Jordan", "phone_code": "+962", "phone_length": 9},
		{"name": "Kazakhstan", "phone_code": "+7", "phone_length": 10},
		{"name": "Kenya", "phone_code": "+254", "phone_length": 9},
		{"name": "Kiribati", "phone_code": "+686", "phone_length": 8},
		{"name": "Kuwait", "phone_code": "+965", "phone_length": 8},
		{"name": "Kyrgyzstan", "phone_code": "+996", "phone_length": 9},
		{"name": "Laos", "phone_code": "+856", "phone_length": 9},
		{"name": "Latvia", "phone_code": "+371", "phone_length": 8},
		{"name": "Lebanon", "phone_code": "+961", "phone_length": 8},
		{"name": "Lesotho", "phone_code": "+266", "phone_length": 9},
		{"name": "Liberia", "phone_code": "+231", "phone_length": 7},
		{"name": "Libya", "phone_code": "+218", "phone_length": 9},
		{"name": "Liechtenstein", "phone_code": "+423", "phone_length": 9},
		{"name": "Lithuania", "phone_code": "+370", "phone_length": 8},
		{"name": "Luxembourg", "phone_code": "+352", "phone_length": 9},
		{"name": "Macao", "phone_code": "+853", "phone_length": 8},
		{"name": "Madagascar", "phone_code": "+261", "phone_length": 9},
		{"name": "Malawi", "phone_code": "+265", "phone_length": 9},
		{"name": "Malaysia", "phone_code": "+60", "phone_length": 10},
		{"name": "Maldives", "phone_code": "+960", "phone_length": 7},
		{"name": "Mali", "phone_code": "+223", "phone_length": 8},
		{"name": "Malta", "phone_code": "+356", "phone_length": 8},
		{"name": "Marshall Islands", "phone_code": "+692", "phone_length": 7},
		{"name": "Martinique", "phone_code": "+596", "phone_length": 9},
		{"name": "Mauritania", "phone_code": "+222", "phone_length": 9},
		{"name": "Mauritius", "phone_code": "+230", "phone_length": 8},
		{"name": "Mayotte", "phone_code": "+262", "phone_length": 9},
		{"name": "Mexico", "phone_code": "+52", "phone_length": 10},
		{"name": "Micronesia", "phone_code": "+691", "phone_length": 7},
		{"name": "Moldova", "phone_code": "+373", "phone_length": 8},
		{"name": "Monaco", "phone_code": "+377", "phone_length": 8},
		{"name": "Mongolia", "phone_code": "+976", "phone_length": 8},
		{"name": "Montenegro", "phone_code": "+382", "phone_length": 8},
		{"name": "Montserrat", "phone_code": "+1-664", "phone_length": 7},
		{"name": "Morocco", "phone_code": "+212", "phone_length": 9},
		{"name": "Mozambique", "phone_code": "+258", "phone_length": 9},
		{"name": "Myanmar", "phone_code": "+95", "phone_length": 9},
		{"name": "Namibia", "phone_code": "+264", "phone_length": 9},
		{"name": "Nauru", "phone_code": "+674", "phone_length": 7},
		{"name": "Nepal", "phone_code": "+977", "phone_length": 10},
		{"name": "Netherlands", "phone_code": "+31", "phone_length": 9},
		{"name": "New Caledonia", "phone_code": "+687", "phone_length": 6},
		{"name": "New Zealand", "phone_code": "+64", "phone_length": 9},
		{"name": "Nicaragua", "phone_code": "+505", "phone_length": 8},
		{"name": "Niger", "phone_code": "+227", "phone_length": 8},
		{"name": "Nigeria", "phone_code": "+234", "phone_length": 10},
		{"name": "Niue", "phone_code": "+683", "phone_length": 4},
		{"name": "Norfolk Island", "phone_code": "+672", "phone_length": 6},
		{"name": "North Korea", "phone_code": "+850", "phone_length": 10},
		{"name": "North Macedonia", "phone_code": "+389", "phone_length": 8},
		{"name": "Norway", "phone_code": "+47", "phone_length": 8},
		{"name": "Oman", "phone_code": "+968", "phone_length": 8},
		{"name": "Pakistan", "phone_code": "+92", "phone_length": 10},
		{"name": "Palau", "phone_code": "+680", "phone_length": 7},
		{"name": "Palestine", "phone_code": "+970", "phone_length": 9},
		{"name": "Panama", "phone_code": "+507", "phone_length": 8},
		{"name": "Papua New Guinea", "phone_code": "+675", "phone_length": 7},
		{"name": "Paraguay", "phone_code": "+595", "phone_length": 9},
		{"name": "Peru", "phone_code": "+51", "phone_length": 9},
		{"name": "Philippines", "phone_code": "+63", "phone_length": 10},
		{"name": "Poland", "phone_code": "+48", "phone_length": 9},
		{"name": "Portugal", "phone_code": "+351", "phone_length": 9},
		{"name": "Puerto Rico", "phone_code": "+1-787", "phone_length": 7},
		{"name": "Qatar", "phone_code": "+974", "phone_length": 8},
		{"name": "Réunion", "phone_code": "+262", "phone_length": 9},
		{"name": "Romania", "phone_code": "+40", "phone_length": 9},
		{"name": "Russia", "phone_code": "+7", "phone_length": 10},
		{"name": "Rwanda", "phone_code": "+250", "phone_length": 9},
		{"name": "Saint Barthélemy", "phone_code": "+590", "phone_length": 9},
		{"name": "Saint Helena", "phone_code": "+290", "phone_length": 4},
		{"name": "Saint Kitts and Nevis", "phone_code": "+1-869", "phone_length": 7},
		{"name": "Saint Lucia", "phone_code": "+1-758", "phone_length": 7},
		{"name": "Saint Martin", "phone_code": "+590", "phone_length": 9},
		{"name": "Saint Pierre and Miquelon", "phone_code": "+508", "phone_length": 6},
		{"name": "Saint Vincent and the Grenadines", "phone_code": "+1-784", "phone_length": 7},
		{"name": "Samoa", "phone_code": "+685", "phone_length": 5},
		{"name": "San Marino", "phone_code": "+378", "phone_length": 9},
		{"name": "Sao Tome and Principe", "phone_code": "+239", "phone_length": 7},
		{"name": "Saudi Arabia", "phone_code": "+966", "phone_length": 9},
		{"name": "Senegal", "phone_code": "+221", "phone_length": 9},
		{"name": "Serbia", "phone_code": "+381", "phone_length": 8},
		{"name": "Seychelles", "phone_code": "+248", "phone_length": 7},
		{"name": "Sierra Leone", "phone_code": "+232", "phone_length": 8},
		{"name": "Singapore", "phone_code": "+65", "phone_length": 8},
		{"name": "Sint Maarten", "phone_code": "+1-721", "phone_length": 7},
		{"name": "Slovakia", "phone_code": "+421", "phone_length": 9},
		{"name": "Slovenia", "phone_code": "+386", "phone_length": 8},
		{"name": "Solomon Islands", "phone_code": "+677", "phone_length": 5},
		{"name": "Somalia", "phone_code": "+252", "phone_length": 9},
		{"name": "South Africa", "phone_code": "+27", "phone_length": 9},
		{"name": "South Korea", "phone_code": "+82", "phone_length": 10},
		{"name": "South Sudan", "phone_code": "+211", "phone_length": 9},
		{"name": "Spain", "phone_code": "+34", "phone_length": 9},
		{"name": "Sri Lanka", "phone_code": "+94", "phone_length": 9},
		{"name": "Sudan", "phone_code": "+249", "phone_length": 9},
		{"name": "Suriname", "phone_code": "+597", "phone_length": 6},
		{"name": "Svalbard and Jan Mayen", "phone_code": "+47", "phone_length": 8},
		{"name": "Sweden", "phone_code": "+46", "phone_length": 9},
		{"name": "Switzerland", "phone_code": "+41", "phone_length": 9},
		{"name": "Syria", "phone_code": "+963", "phone_length": 9},
		{"name": "Taiwan", "phone_code": "+886", "phone_length": 9},
		{"name": "Tajikistan", "phone_code": "+992", "phone_length": 9},
		{"name": "Tanzania", "phone_code": "+255", "phone_length": 9},
		{"name": "Thailand", "phone_code": "+66", "phone_length": 9},
		{"name": "Timor-Leste", "phone_code": "+670", "phone_length": 8},
		{"name": "Togo", "phone_code": "+228", "phone_length": 8},
		{"name": "Tokelau", "phone_code": "+690", "phone_length": 4},
		{"name": "Tonga", "phone_code": "+676", "phone_length": 5},
		{"name": "Trinidad and Tobago", "phone_code": "+1-868", "phone_length": 7},
		{"name": "Tunisia", "phone_code": "+216", "phone_length": 8},
		{"name": "Turkey", "phone_code": "+90", "phone_length": 10},
		{"name": "Turkmenistan", "phone_code": "+993", "phone_length": 8},
		{"name": "Tuvalu", "phone_code": "+688", "phone_length": 5},
		{"name": "Uganda", "phone_code": "+256", "phone_length": 9},
		{"name": "Ukraine", "phone_code": "+380", "phone_length": 9},
		{"name": "United Arab Emirates", "phone_code": "+971", "phone_length": 9},
		{"name": "United Kingdom", "phone_code": "+44", "phone_length": 10},
		{"name": "United States", "phone_code": "+1", "phone_length": 10},
		{"name": "Uruguay", "phone_code": "+598", "phone_length": 8},
		{"name": "Uzbekistan", "phone_code": "+998", "phone_length": 9},
		{"name": "Vanuatu", "phone_code": "+678", "phone_length": 7},
		{"name": "Vatican City", "phone_code": "+379", "phone_length": 8},
		{"name": "Venezuela", "phone_code": "+58", "phone_length": 10},
		{"name": "Vietnam", "phone_code": "+84", "phone_length": 9},
		{"name": "Wallis and Futuna", "phone_code": "+681", "phone_length": 6},
		{"name": "Western Sahara", "phone_code": "+212", "phone_length": 9},
		{"name": "Yemen", "phone_code": "+967", "phone_length": 9},
		{"name": "Zambia", "phone_code": "+260", "phone_length": 9},
		{"name": "Zimbabwe", "phone_code": "+263", "phone_length": 9}
	]
}